create table if not exists properties (
  id bigint generated by default as identity primary key,
  address text not null unique,
  address_key text not null unique,
  owner_approval_limit integer not null default 500,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists tenants (
  id bigint generated by default as identity primary key,
  property_id bigint references properties(id) on delete cascade,
  name text not null,
  email text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists tenants_property_id_idx on tenants(property_id);
create index if not exists tenants_email_idx on tenants(email);

create table if not exists contractors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  trade text not null,
  response_sla_minutes integer not null default 30,
  priority_rank integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists contractors_trade_idx on contractors(trade);

create table if not exists work_orders (
  id bigint generated by default as identity primary key,
  property_id bigint references properties(id),
  tenant_id bigint references tenants(id),
  contractor_id bigint references contractors(id),
  sender_email text not null,
  tenant_name text,
  extracted_address text,
  subject text not null,
  raw_email text not null,
  category text not null,
  priority text not null,
  trade text not null,
  estimated_low integer,
  estimated_high integer,
  owner_limit integer,
  within_limit boolean not null default false,
  tenant_message text,
  status text not null default 'pending_approval',
  tenant_email_message_id text,
  contractor_email_message_id text,
  created_at timestamptz not null default now(),
  dispatched_at timestamptz
);
create index if not exists work_orders_status_idx on work_orders(status);
create index if not exists work_orders_created_at_idx on work_orders(created_at desc);

create table if not exists events (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references work_orders(id) on delete cascade,
  event_type text not null,
  detail text,
  created_at timestamptz not null default now()
);
create index if not exists events_work_order_id_idx on events(work_order_id);

insert into properties(address,address_key,owner_approval_limit)
values
  ('18 Lakeview Rd, Como','18 lakeview rd como',500),
  ('Unit 7, 42 Oxford St, Leederville','unit 7 42 oxford st leederville',600),
  ('9 Park Lane, Victoria Park','9 park lane victoria park',350),
  ('31 River View, East Perth','31 river view east perth',500)
on conflict (address) do update set
  address_key=excluded.address_key,
  owner_approval_limit=excluded.owner_approval_limit,
  active=true;

insert into tenants(property_id,name,email)
select p.id, x.name, x.email
from (values
  ('18 Lakeview Rd, Como','Sarah Lee','sarah.lee@example.com'),
  ('Unit 7, 42 Oxford St, Leederville','Daniel Wong','daniel.wong@example.com'),
  ('9 Park Lane, Victoria Park','Aisha Khan','aisha.khan@example.com'),
  ('31 River View, East Perth','Michael Chen','michael.chen@example.com')
) as x(address,name,email)
join properties p on p.address=x.address
where not exists (select 1 from tenants t where t.email=x.email);

insert into contractors(name,email,trade,response_sla_minutes,priority_rank)
select * from (values
  ('Westside Plumbing & Gas','dispatch+gas@example.com','Gas fitter',15,1),
  ('RapidFlow Plumbing','dispatch+plumbing@example.com','Plumber',30,1),
  ('Westline Electrical','dispatch+electrical@example.com','Electrician',30,1),
  ('SecureKey Locksmiths','dispatch+locksmith@example.com','Locksmith',30,1),
  ('Metro Property Services','dispatch+maintenance@example.com','Maintenance tech',240,1)
) as x(name,email,trade,response_sla_minutes,priority_rank)
where not exists (
  select 1 from contractors c where c.name=x.name and c.trade=x.trade
);
